name: Deploy Docs to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}-mkdocs
          path: .cache
          restore-keys: |
            mkdocs-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy with mkdocs gh-deploy
        run: mkdocs gh-deploy --force --clean
